platform :ios, '8.0'

use_frameworks!

target 'xingxingEdu' do
    pod 'BaiduMapKit'
    pod 'DFCommon', '~> 1.3.9'
    pod 'UMengSocial'
    pod 'RETableViewManager', '~> 1.6'
    pod 'BeeCloud'
    pod 'RongCloudIMKitWithVoip'
    pod 'JSONModel','~>1.2.0'
    
end


